nelmio_api_doc:
    documentation:
        info:
            title: Visitor test app
            description: OA for visitor test app
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc